// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: sys_stats_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SysStatsService_ReportSysStats_FullMethodName = "/sysStatsService/reportSysStats"
	SysStatsService_ReportHostInfo_FullMethodName = "/sysStatsService/reportHostInfo"
)

// SysStatsServiceClient is the client API for SysStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysStatsServiceClient interface {
	ReportSysStats(ctx context.Context, in *SysStats, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReportHostInfo(ctx context.Context, in *HostInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sysStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSysStatsServiceClient(cc grpc.ClientConnInterface) SysStatsServiceClient {
	return &sysStatsServiceClient{cc}
}

func (c *sysStatsServiceClient) ReportSysStats(ctx context.Context, in *SysStats, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SysStatsService_ReportSysStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysStatsServiceClient) ReportHostInfo(ctx context.Context, in *HostInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SysStatsService_ReportHostInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysStatsServiceServer is the server API for SysStatsService service.
// All implementations must embed UnimplementedSysStatsServiceServer
// for forward compatibility
type SysStatsServiceServer interface {
	ReportSysStats(context.Context, *SysStats) (*emptypb.Empty, error)
	ReportHostInfo(context.Context, *HostInfo) (*emptypb.Empty, error)
	mustEmbedUnimplementedSysStatsServiceServer()
}

// UnimplementedSysStatsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSysStatsServiceServer struct {
}

func (UnimplementedSysStatsServiceServer) ReportSysStats(context.Context, *SysStats) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSysStats not implemented")
}
func (UnimplementedSysStatsServiceServer) ReportHostInfo(context.Context, *HostInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportHostInfo not implemented")
}
func (UnimplementedSysStatsServiceServer) mustEmbedUnimplementedSysStatsServiceServer() {}

// UnsafeSysStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysStatsServiceServer will
// result in compilation errors.
type UnsafeSysStatsServiceServer interface {
	mustEmbedUnimplementedSysStatsServiceServer()
}

func RegisterSysStatsServiceServer(s grpc.ServiceRegistrar, srv SysStatsServiceServer) {
	s.RegisterService(&SysStatsService_ServiceDesc, srv)
}

func _SysStatsService_ReportSysStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysStats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysStatsServiceServer).ReportSysStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysStatsService_ReportSysStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysStatsServiceServer).ReportSysStats(ctx, req.(*SysStats))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysStatsService_ReportHostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysStatsServiceServer).ReportHostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysStatsService_ReportHostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysStatsServiceServer).ReportHostInfo(ctx, req.(*HostInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// SysStatsService_ServiceDesc is the grpc.ServiceDesc for SysStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysStatsService",
	HandlerType: (*SysStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "reportSysStats",
			Handler:    _SysStatsService_ReportSysStats_Handler,
		},
		{
			MethodName: "reportHostInfo",
			Handler:    _SysStatsService_ReportHostInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sys_stats_service.proto",
}
